### ISSUE TITLE
Rename internal name

### ISSUE THREAD

**Issue by NatoBoram** [Permaweb/Host#3]
Currently, the program refers to itself as `Gi` for "Git to IPNS". Renaming it would require to add a `/cmd/<name>` directory so the command can have an explicit name rather than "Host" and to move the configs from `~/.config/gi` to `~/.config/<name>`.

@leshokunin What name should I use internally?

**Comment by tetrisgm** [comment]
How about GitHub to Permaweb?

**Comment by NatoBoram** [comment]
> How about GitHub to Permaweb?

That would be a **human-readable** name, for which there's already *Permaweb Host*. I need an **internal** name. Commands don't usually contain spaces in them, nor can functions and variables.

Moreover, the project isn't specific to GitHub, it can take any Git URL.

**Comment by tetrisgm** [comment]
Probably permawebhost then?

**Comment by NatoBoram** [comment]
Hm, it's quite a ~~mouthful~~ handful :thinking: 

What about `pwhost`?

**Comment by tetrisgm** [comment]
This was done, right?

**Comment by NatoBoram** [comment]
Oh, yeah, it's done!
